name: 'Nextflow pytest-workflow'
description: 'Setups up nextflow and pytest-workflow'
inputs:
  pytest_tags:  # id of input
    description: 'List of tags for pytest-workflow'
    required: true
    default: ''
  nxf_version:  # id of input
    description: 'Nextflow version to use'
    required: true
    default: '20.11.0-edge'
# outputs:
#   logs:
#     description: "Nextflow and pytest-workflow logs number"
#     value: ${{ steps.upload-logs.outputs.logs }}
runs:
  using: "composite"
  steps:
      - name: Install Nextflow
        env:
          NXF_VER: ${{ inputs.nxf_version }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        env:
          NXF_ANSI_LOG: false
        run: python -m pip install --upgrade pip pytest-workflow

      # Test the module
      - run: pytest ---tag ${{ inputs.pytest_tags}} --symlink --wt 2

      - name: Upload logs on failure
        if: failure()
        id: upload-logs
        uses: actions/upload-artifact@v2
        with:
          name: logs ${{ inputs.pytest_tags }} ${{ inputs.nxf_version }}
          path: |
            /tmp/pytest_workflow_*/*/.nextflow.log
            /tmp/pytest_workflow_*/*/log.out
            /tmp/pytest_workflow_*/*/log.err
