name: 'Nextflow pytest-workflow'
description: 'Setups up nextflow and pytest-workflow'
inputs:
  pytest_tags:  # id of input
    description: 'List of tags for pytest-workflow'
    required: true
    default: ''
  nxf_version:  # id of input
    description: 'Nextflow version to use'
    required: true
    default: '20.11.0-edge'
# outputs:
#   logs:
#     description: "Nextflow and pytest-workflow logs number"
#     value: ${{ steps.upload-logs.outputs.logs }}
runs:
  using: "composite"
  steps:
      - name: Install Nextflow
        shell: bash
        env:
          NXF_VER: ${{ inputs.nxf_version }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Install dependencies
        env:
          NXF_ANSI_LOG: false
        run: python3 -m pip install --upgrade pip pytest-workflow
        shell: bash

      # Test the module
      - run: pytest ---tag ${{ inputs.pytest_tags}} --symlink --wt 2
        shell: bash