name: Dogfood
on: [push]

jobs:
  ci_test:
    runs-on: ubuntu-latest
    name: CI Test
    strategy:
      matrix:
        nxf_version: [20.11.0-edge]
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Nextflow pytest-workflow
        uses: ./.
        with:
          pytest_tags: 'default --tag docker'
          nxf_version: ${{ matrix.nxf_version }}

      - name: Nextflow pytest-workflow
        uses: ./.
        with:
          pytest_tags: 'nextflow'
          nxf_version: ${{ matrix.nxf_version }}