name: Dogfood
on: [push]

jobs:
  ci_test:
    runs-on: ubuntu-latest
    name: CI Test
    strategy:
      matrix:
        nxf_version: [20.11.0-edge]
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v2
      - name: Nextflow pytest-workflow
        uses: ./action.yml
        with:
          pytest_tags: 'fastqc'
          nxf_version: ${{ matrix.nxf_version }}
